name: Claude Manual Trigger

on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'Pull Request number to comment on'
        required: false
        type: string
      issue_number:
        description: 'Issue number to comment on'
        required: false
        type: string
      comment_body:
        description: 'Comment body (must include @claude)'
        required: true
        default: '@claude implement this feature based on the PR description'
        type: string

jobs:
  trigger-claude:
    runs-on: ubuntu-latest
    steps:
      - name: Create comment to trigger Claude
        env:
          # Use a PAT from a real user account, not github-actions bot
          GITHUB_TOKEN: ${{ secrets.CLAUDE_TRIGGER_TOKEN }}
          PR_NUMBER: ${{ github.event.inputs.pr_number }}
          ISSUE_NUMBER: ${{ github.event.inputs.issue_number }}
          COMMENT_BODY: ${{ github.event.inputs.comment_body }}
        run: |
          if [ -n "$PR_NUMBER" ]; then
            echo "Creating comment on PR #$PR_NUMBER"
            curl -X POST \
              -H "Authorization: token $GITHUB_TOKEN" \
              -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/repos/${{ github.repository }}/issues/$PR_NUMBER/comments \
              -d "{\"body\": \"$COMMENT_BODY\"}"
          elif [ -n "$ISSUE_NUMBER" ]; then
            echo "Creating comment on Issue #$ISSUE_NUMBER"
            curl -X POST \
              -H "Authorization: token $GITHUB_TOKEN" \
              -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/repos/${{ github.repository }}/issues/$ISSUE_NUMBER/comments \
              -d "{\"body\": \"$COMMENT_BODY\"}"
          else
            echo "❌ Either pr_number or issue_number must be provided"
            exit 1
          fi