name: Linear Webhook Handler

on:
  repository_dispatch:
    types: [linear-webhook]

jobs:
  handle-linear-event:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      
      - name: Process Linear webhook
        run: |
          echo "Received Linear webhook event"
          echo "Event type: ${{ github.event.action }}"
          echo "Payload: ${{ toJson(github.event.client_payload) }}"
          
          # Check if this is a label update event
          if [[ "${{ github.event.client_payload.type }}" == "Issue" ]]; then
            if [[ "${{ github.event.client_payload.action }}" == "update" ]]; then
              # Check if "ready for Claude" label was added
              LABELS=$(echo '${{ toJson(github.event.client_payload.data.labels) }}' | jq -r '.[]')
              if echo "$LABELS" | grep -q "ready for Claude"; then
                echo "Triggering refactoring workflow..."
                gh workflow run linear-claude-refactor.yml \
                  -f linear_issue_id=${{ github.event.client_payload.data.identifier }}
              fi
            fi
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}